# -*- mode: python ; coding: utf-8 -*-
"""SONIC AI - PyInstaller Spec File.

Build command:
    pyinstaller sonic.spec

Output: dist/SONIC-AI.exe
"""
from PyInstaller.utils.hooks import collect_data_files, collect_submodules
from pathlib import Path
import os

block_cipher = None

datas = [
    ("config", "config"),
    ("auth", "auth"),
    ("core", "core"),
    ("sonic-frontend-theme", "sonic-frontend-theme"),
    ("updater", "updater"),
    ("bootstrap", "bootstrap"),
    ("version.py", "."),
    ("config/sonic.ico", "config"),
]

hiddenimports = [
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.sip",
    "PyQt6.QtSvg",
    "PyQt6.QtSvgWidgets",
    "actions.smart_file_manager",
    "actions.utility_controls",
    "actions.computer_settings",
    "actions.file_controller",
    "actions.file_processor",
    "actions.web_search",
    "actions.browser_control",
    "actions.desktop",
    "actions.open_app",
    "actions.code_helper",
    "actions.dev_agent",
    "actions.system_monitor",
    "actions.proactive",
    "actions.background_monitor",
    "actions.screen_processor",
    "actions.send_message",
    "actions.reminder",
    "actions.youtube_video",
    "actions.weather_report",
    "actions.flight_finder",
    "actions.game_updater",
    "actions.computer_control",
    "memory.memory_manager",
    "memory.db",
    "memory.models",
    "memory.retrieval",
    "memory.extractor",
    "memory.context_builder",
    "memory.consolidation",
    "memory.cloud_sync",
    "memory.config_manager",
    "auth.core",
    "auth.secrets",
    "auth.firestore_sync",
    "emotion",
    "emotion.models",
    "emotion.detector",
    "emotion.vocabulary",
    "emotion.personality",
    "coding.adapter",
    "coding.intent_detector",
    "coding.process",
    "coding.workspace",
    "coding.verification",
    "updater",
    "updater.ui",
    "updater.startup",
    "updater.migrations",
    "bootstrap",
    "bootstrap.detector",
    "bootstrap.installer",
    "bootstrap.state",
    "bootstrap.ui",
    "location",
    "location.models",
    "location.provider",
    "location.cache",
    "reliability",
    "reliability.classifier",
    "reliability.retry",
    "reliability.paths",
    "reliability.verify",
    "reliability.validator",
    "splash",
    "PyQt6.QtMultimedia",
    "PyQt6.QtMultimediaWidgets",
    "core.plugin_loader",
    "core.undo",
    "core.confirm",
    "core.audio_devices",
    "core.llm_client",
    "version",
    "psutil",
    "pyperclip",
    "pyautogui",
    "sounddevice",
    "numpy",
    "google.genai",
    "google.generativeai",
    "requests",
    "bs4",
    "PIL",
    "cv2",
    "mss",
    "send2trash",
    "qrcode",
    "pycaw",
    "comtypes",
    "ctypes.wintypes",
    "win32com.client",
    "pywin32",
    "psutil._windows",
]

a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "scipy",
        "pandas",
        "notebook",
        "IPython",
        "pytest",
        "PyQt5",
        "pygame",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="SONIC-AI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="config/sonic.ico",
    version_info=None,
)
